# -*- coding: utf-8 -*-
"""Лаб7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MCEc85DAvobaZkB7ICY_M5an1uyp4nyk
"""

import numpy as np
import matplotlib.pyplot as plt

def proizv(signal, dt):
    d = np.diff(signal) / dt
    d = np.append(d, d[-1])
    return d

def integr(signal, dt):
    s = 0
    result = np.zeros(len(signal))
    for i in range(len(signal)-1):
        s += signal[i] * dt
        result[i+1] = s
    return result

fs = 7000
t_start = -1
t_end = 1
N = int(fs * (t_end - t_start) + 1)
t = np.linspace(t_start, t_end, N)
dt = t[1] - t[0]
signal = t * 3 * np.abs(np.sin(t * 60))
integr_signal = integr(signal, dt)
der_signal = proizv(signal, dt)

plt.figure(figsize=(12,8))
plt.subplot(3,1,1)
plt.plot(t, signal)
plt.title("Исходный сигнал U(t) = 3t·|sin(60t)|")
plt.grid()
plt.subplot(3,1,2)
plt.plot(t, integr_signal)
plt.title("Интеграл U(t)")
plt.grid()
plt.subplot(3,1,3)
plt.plot(t, der_signal)
plt.title("Производная U(t)")
plt.grid()
plt.tight_layout()
plt.show()
#2
signal_lin = 2*t + 1
der_lin = proizv(signal_lin, dt)
print("Тест линейной функции: производная =", der_lin[0])

plt.figure(figsize=(10,6))
plt.subplot(2,1,1)
plt.plot(t, signal_lin)
plt.title("Линейная функция: f(t) = 2t + 1")
plt.grid()
plt.subplot(2,1,2)
plt.plot(t, der_lin)
plt.title("Производная линейной функции (должна быть = 2)")
plt.grid()
plt.tight_layout()
plt.show()
#3
signal_quad = t**2
der_quad = proizv(signal_quad, dt)
der_quad_theor = 2*t

print("Тест квадратичной функции:")
print("  Производная в 0 (численная) =", der_quad[N//2])
print("  Производная в 0 (аналитическая) =", 0)

plt.figure(figsize=(10,6))
plt.subplot(2,1,1)
plt.plot(t, signal_quad, label='f(t) = t²')
plt.title("Квадратичная функция")
plt.grid()
plt.legend(loc='upper left')

plt.subplot(2,1,2)
plt.plot(t, der_quad, 'r', label='Численная производная')
plt.plot(t, der_quad_theor, 'k--', label='Аналитическая: 2t')
plt.title("Производная квадратичной функции")
plt.grid()
plt.legend(loc='upper left')

plt.tight_layout()
plt.show()